apiVersion: v1
kind: Service
metadata:
  name: triceratops-transport
  labels:
    service: triceratops-transport
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    service: triceratops-transport
	{{- include "common.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80      # Service port
      targetPort: 8080 # Container port
  type: ClusterIP     # Internal service within the Kubernetes cluster
